name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js (optional)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 'Deploy to Azure Static Web Apps'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # required: set in repo secrets
          repo_token: ${{ secrets.GITHUB_TOKEN }} # used for automatic GitHub checks
          action: "upload"
          app_location: "project1" # App source code path in the repo (folder with your HTML/CSS)
          api_location: ""
          output_location: ""
